In [2]:
import pandas as pd
import mysql.connector

import numpy as np

### Cargar nuestra base de datos con un csv a partir de la librería mysql.connector 

Antes de cargar los datos, veamos los valores únicos de cada columna para revisar el diseño de la base de datos

In [61]:
# Leer el CSV
df_sale = pd.read_csv("madrid_sale_properties_processed_1.csv")

In [62]:
df_sale

url   property_id  \
0     https://www.pisos.com/comprar/piso-recoletos28...  4.756077e+10   
1     https://www.pisos.com/comprar/piso-universidad...  5.003730e+10   
2     https://www.pisos.com/comprar/piso-goya28009-4...  4.501932e+10   
3     https://www.pisos.com/comprar/piso-opanel28019...  5.173469e+10   
4     https://www.pisos.com/comprar/piso-rejas28022-...  5.422137e+10   
...                                                 ...           ...   
2997  https://www.pisos.com/comprar/piso-puente_de_v...  5.256348e+10   
2998  https://www.pisos.com/comprar/piso-ciudad_line...  5.341673e+10   
2999  https://www.pisos.com/comprar/atico-valdemarin...  5.421518e+10   
3000  https://www.pisos.com/comprar/piso-trafalgar28...  5.338242e+10   
3001  https://www.pisos.com/comprar/atico-sol_barrio...  4.843106e+10   

      price_eur                barrio            distrito   latitude  \
0     9500000.0             Recoletos           Salamanca  40.422116   
1      840000.0  Universidad-Malasaña              Centro  40.422312   
2     3600000.0                  Goya           Salamanca  40.424364   
3      285000.0                Opañel         Carabanchel  40.389100   
4      539000.0                 Rejas            San Blas  40.442042   
...         ...                   ...                 ...        ...   
2997   279000.0              Portazgo  Puente de Vallecas  40.383712   
2998   411000.0          Pueblo Nuevo       Ciudad Lineal  40.426333   
2999  1550000.0            Valdemarín     Moncloa-Aravaca  40.465343   
3000  2490000.0             Trafalgar            Chamberí  40.435597   
3001  2460000.0                   Sol              Centro  40.415001   

      longitude                  scraped_at  \
0     -3.683149  2025-05-28T17:29:28.477101   
1     -3.706137  2025-05-28T17:29:30.304660   
2     -3.670577  2025-05-28T17:29:32.075647   
3     -3.719900  2025-05-28T17:29:33.855489   
4     -3.575920  2025-05-28T17:29:35.657174   
...         ...                         ...   
2997  -3.650452  2025-05-28T19:00:00.644476   
2998  -3.638205  2025-05-28T19:00:02.401578   
2999  -3.762967  2025-05-28T19:00:04.332734   
3000  -3.700479  2025-05-28T19:00:06.100435   
3001  -3.706658  2025-05-28T19:00:07.840335   

                                            description  \
0     Exclusiva Propiedad en Recoletos junto al Parq...   
1     UNICA INMOBILIARIA ofrece este impresionante p...   
2     UNICA INMOBILIARIA ofrece este impresionante i...   
3     Piso de 2 habitaciones de 60m² en madrid(28019...   
4     Espléndida vivienda exterior con una superfici...   
...                                                 ...   
2997  Agencia inmobiliaria de MADRID VALLECAS - Zona...   
2998  La Inmobiliaria Internacional CPM gestiona est...   
2999  Lujo, vistas y confort a un paso de Madrid Des...   
3000  *********grupo inmara inmobiliaria************...   
3001  Este espectacular ático de 140 m² se encuentra...   

     energy_cert_classification  ... superficie_construida superficie_util  \
0                    En trámite  ...                 499.0           499.0   
1                    En trámite  ...                 109.0            95.0   
2                    En trámite  ...                 379.0             NaN   
3                    Disponible  ...                  60.0            60.0   
4                    Disponible  ...                 127.0           101.0   
...                         ...  ...                   ...             ...   
2997                 Disponible  ...                 113.0             NaN   
2998     Pendiente de completar  ...                 130.0           120.0   
2999                 Disponible  ...                 239.0             NaN   
3000                 En trámite  ...                 185.0           160.0   
3001     Pendiente de completar  ...                 139.0             NaN   

      terraza  trastero vidrios_dobles energy_consumption_kwh_m2_yr  \
0       False     False     

In [63]:
# Leer el CSV
df_rental = pd.read_csv("madrid_rental_properties_processed_1.csv")

In [64]:
df_rental

url   property_id  \
0     https://www.pisos.com/alquilar/atico-salamanca...  5.174066e+10   
1     https://www.pisos.com/alquilar/atico-rio_rosas...  5.423369e+10   
2     https://www.pisos.com/alquilar/piso-salamanca_...  5.423565e+10   
3     https://www.pisos.com/alquilar/piso-fuente_del...  5.752243e+08   
4     https://www.pisos.com/alquilar/piso-justicia_c...  5.252461e+10   
...                                                 ...           ...   
2180  https://www.pisos.com/alquilar/chalet_pareado-...  1.036083e+07   
2181  https://www.pisos.com/alquilar/chalet_adosado-...  3.839881e+10   
2182  https://www.pisos.com/alquilar/chalet_unifamil...  9.417805e+10   
2183  https://www.pisos.com/alquilar/piso-el_soto_de...  5.092987e+10   
2184  https://www.pisos.com/alquilar/piso-la_moralej...  5.425132e+10   

      price_eur_pm            barrio   distrito   latitude  longitude  \
0          10000.0        Castellana  Salamanca  40.434281  -3.686286   
1           1450.0         Río Rosas   Chamberí  40.438612  -3.699901   
2           2200.0        Castellana  Salamanca  40.435237  -3.683515   
3           1700.0  Fuente del Berro  Salamanca  40.429047  -3.666474   
4           2650.0   Justicia-Chueca     Centro  40.422607  -3.699196   
...            ...               ...        ...        ...        ...   
2180        4300.0               NaN        NaN  40.516174  -3.640806   
2181        6000.0               NaN        NaN  40.516126  -3.640197   
2182        6000.0               NaN        NaN  40.521171  -3.648401   
2183        5500.0               NaN        NaN  40.519891  -3.642340   
2184        4750.0               NaN        NaN  40.507050  -3.624863   

                      scraped_at  \
0     2025-05-28T19:53:30.586256   
1     2025-05-28T19:53:32.370621   
2     2025-05-28T19:53:34.120400   
3     2025-05-28T19:53:35.912036   
4     2025-05-28T19:53:37.641884   
...                          ...   
2180  2025-05-28T20:58:10.540537   
2181  2025-05-28T20:58:12.307336   
2182  2025-05-28T20:58:14.052258   
2183  2025-05-28T20:58:15.822177   
2184  2025-05-28T20:58:17.572090   

                                            description  \
0     DISPONIBLE DE MANERA INMEDIATA HousinGo presen...   
1     DISPONIBLE A PARTIR DEL 25 DE JUNIO DE 2025 Ho...   
2     DISPONIBLE A PARTIR DEL 23 DE JUNIO DE 2025! D...   
3     ¡Oportunidad de alquiler! Este luminoso piso e...   
4     ¡¡Piso totalmente reformado, a estrenar, 2 dor...   
...                                                 ...   
2180  MAGNAPOL ALQUILA Luminoso Chalet Pareado de 27...   
2181  MAGNAPOL ALQUILA en EXCLUSIVA, amplio Chalet a...   
2182  MAGNAPOL ALQUILA. Estupendo Chalet unifamiliar...   
2183  Este impresionante piso en alquiler se encuent...   
2184  Gilmar pone a su disposición este excelente pi...   

     energy_cert_classification  ... superficie_util terraza  trastero  \
0        Pendiente de completar  ...             NaN    True     False   
1                    En trámite  ...             NaN    True     False   
2                    En trámite  ...           100.0   False     False   
3                    En trámite  ...            50.0    True     False   
4                    Disponible  ...            77.0   False     False   
...                         ...  ...             ...     ...       ...   
2180                 En trámite  ...           270.0    True     False   
2181                 En trámite  ...           270.0   False     False   
2182                 En trámite  ...           350.0   False     False   
2183                 En trámite  ...           250.0    True      True   
2184                 En trámite  ...             NaN   False     False   

      vidrios_dobles energy_consumption_kwh_m2_yr  \
0              False                          NaN   
1              False                          NaN   
2              False                          NaN   
3              False                          NaN   
4 

### Comprobar los valores de cada columna

In [15]:
df_sale.columns

Index(['url', 'property_id', 'price_eur', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica'],
      dtype='object')

In [16]:
df_rental.columns

Index(['url', 'property_id', 'price_eur_pm', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica',
       'acepta_mascotas'],
      dtype='object')

Identificador de cada piso 

In [8]:
df_rental.shape

(2185, 42)

In [10]:
df_rental["property_id"].unique

<bound method Series.unique of 0       5.174066e+10
1       5.423369e+10
2       5.423565e+10
3       5.752243e+08
4       5.252461e+10
            ...     
2180    1.036083e+07
2181    3.839881e+10
2182    9.417805e+10
2183    5.092987e+10
2184    5.425132e+10
Name: property_id, Length: 2185, dtype: float64>

hay el mismo numero de filas que de valores unicos, no se repiten

In [14]:
df_sale.shape

(3002, 41)

In [13]:
df_sale["property_id"].unique

<bound method Series.unique of 0       4.756077e+10
1       5.003730e+10
2       4.501932e+10
3       5.173469e+10
4       5.422137e+10
            ...     
2997    5.256348e+10
2998    5.341673e+10
2999    5.421518e+10
3000    5.338242e+10
3001    4.843106e+10
Name: property_id, Length: 3002, dtype: float64>

El sale tampoco se repiten

In [67]:
df_sale["acepta_mascotas"] = None

In [68]:
df_rental.columns

Index(['url', 'property_id', 'price_eur_pm', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica',
       'acepta_mascotas'],
      dtype='object')

In [71]:
col = ['energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad',
       'terraza', 'trastero', 'vidrios_dobles',
       'orientacion_list','acepta_mascotas']

In [72]:
[df_rental[columna].unique() for columna in col]

[array(['Pendiente de completar', 'En trámite', 'Disponible',
        'No indicado', 'Exento'], dtype=object),
 array([nan, 'D', 'E', 'C', 'F', 'G', 'B', 'A'], dtype=object),
 array([nan, 'D', 'E', 'C', 'G', 'F', 'B', 'A'], dtype=object),
 array([False,  True]),
 array([ True, False]),
 array([nan, True], dtype=object),
 array([nan, 'Más de 50 años', 'Entre 20 y 30 años', 'Entre 30 y 50 años',
        'Entre 5 y 10 años', 'Menos de 5 años', 'Entre 10 y 20 años'],
       dtype=object),
 array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([ True, False]),
 array(['A estrenar', 'En buen estado', nan, 'Reformado', 'A reformar'],
       dtype=object),
 array([ True, False]),
 array([ True, False]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([False,  True]),
 array([nan, "['S']", "['NO']", "['SE']", "['E']", "['N

In [21]:
df_sale.columns

Index(['url', 'property_id', 'price_eur', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica'],
      dtype='object')

In [73]:
[df_sale[columna].unique() for columna in col]

[array(['En trámite', 'Disponible', 'No indicado',
        'Pendiente de completar', 'Exento'], dtype=object),
 array([nan, 'E', 'C', 'D', 'A', 'F', 'G', 'B'], dtype=object),
 array([nan, 'D', 'E', 'A', 'F', 'C', 'B', 'G'], dtype=object),
 array([False,  True]),
 array([ True, False]),
 array([True, nan, False], dtype=object),
 array([nan, 'Más de 50 años', 'Entre 20 y 30 años', 'Entre 30 y 50 años',
        'Menos de 5 años', 'Entre 10 y 20 años', 'Entre 5 y 10 años'],
       dtype=object),
 array([ True, False]),
 array([ True, False]),
 array([ True, False]),
 array([ True, False]),
 array([False,  True]),
 array([ True, False]),
 array(['A estrenar', 'En buen estado', 'Reformado', nan, 'A reformar'],
       dtype=object),
 array([ True, False]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array(["['E']", "['E', 'S']", "['S']", nan, "['

conectamos con la base de datos para hacer la insercion

In [74]:
conn.close()
cursor.close()

True

In [75]:
# Conexión a MySQL
conn = mysql.connector.connect(
    host="localhost", 
    user="root", 
    password="contraseña",
    database="pisos3"
)

In [76]:
cursor = conn.cursor()

Una vez conectada la base de datos vamos a concatenar los dos dataframe, para ello necesitamos unificar los campos 

### Unificar precio y tipo

In [77]:
df_rental = df_rental.rename(
    columns={"price_eur_pm": "price_eur"}
)

In [78]:
df_rental.columns

Index(['url', 'property_id', 'price_eur', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica',
       'acepta_mascotas'],
      dtype='object')

In [79]:
df_rental["price_kind"]   = "rent_month"
df_rental["listing_type"] = "rental"    # para identificarlos mejor 

In [80]:
df_rental["price_kind"].unique()

array(['rent_month'], dtype=object)

In [81]:
df_rental["listing_type"].unique()

array(['rental'], dtype=object)

In [82]:
df_sale["price_kind"]   = "sale_price"
df_sale["listing_type"] = "sale"

In [83]:
df_sale["price_kind"].unique()

array(['sale_price'], dtype=object)

In [84]:
df_sale["listing_type"].unique()

array(['sale'], dtype=object)

### Las columnas de valor energetico de sale no las vamos a usar así que serán borradas

In [ ]:
# de momento se guardan
#df_sale = df_sale.drop(columns=["energy_consumption_kwh_m2_yr", "energy_emissions_kg_co2_m2_yr"])

### Comprobar orden columnas y concatenar

In [85]:
df_sale.columns

Index(['url', 'property_id', 'price_eur', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica',
       'acepta_mascotas', 'price_kind', 'listing_type'],
      dtype='object')

In [88]:
df_rental.columns == df_sale.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [89]:
df = pd.concat([df_rental, df_sale], ignore_index=True)
df = df.drop_duplicates()

In [90]:
df.shape

(5187, 44)

In [91]:
df_sale.shape + df_rental.shape

(3002, 44, 2185, 44)

In [93]:
df

url   property_id  \
0     https://www.pisos.com/alquilar/atico-salamanca...  5.174066e+10   
1     https://www.pisos.com/alquilar/atico-rio_rosas...  5.423369e+10   
2     https://www.pisos.com/alquilar/piso-salamanca_...  5.423565e+10   
3     https://www.pisos.com/alquilar/piso-fuente_del...  5.752243e+08   
4     https://www.pisos.com/alquilar/piso-justicia_c...  5.252461e+10   
...                                                 ...           ...   
5182  https://www.pisos.com/comprar/piso-puente_de_v...  5.256348e+10   
5183  https://www.pisos.com/comprar/piso-ciudad_line...  5.341673e+10   
5184  https://www.pisos.com/comprar/atico-valdemarin...  5.421518e+10   
5185  https://www.pisos.com/comprar/piso-trafalgar28...  5.338242e+10   
5186  https://www.pisos.com/comprar/atico-sol_barrio...  4.843106e+10   

      price_eur            barrio            distrito   latitude  longitude  \
0       10000.0        Castellana           Salamanca  40.434281  -3.686286   
1        1450.0         Río Rosas            Chamberí  40.438612  -3.699901   
2        2200.0        Castellana           Salamanca  40.435237  -3.683515   
3        1700.0  Fuente del Berro           Salamanca  40.429047  -3.666474   
4        2650.0   Justicia-Chueca              Centro  40.422607  -3.699196   
...         ...               ...                 ...        ...        ...   
5182   279000.0          Portazgo  Puente de Vallecas  40.383712  -3.650452   
5183   411000.0      Pueblo Nuevo       Ciudad Lineal  40.426333  -3.638205   
5184  1550000.0        Valdemarín     Moncloa-Aravaca  40.465343  -3.762967   
5185  2490000.0         Trafalgar            Chamberí  40.435597  -3.700479   
5186  2460000.0               Sol              Centro  40.415001  -3.706658   

                      scraped_at  \
0     2025-05-28T19:53:30.586256   
1     2025-05-28T19:53:32.370621   
2     2025-05-28T19:53:34.120400   
3     2025-05-28T19:53:35.912036   
4     2025-05-28T19:53:37.641884   
...                          ...   
5182  2025-05-28T19:00:00.644476   
5183  2025-05-28T19:00:02.401578   
5184  2025-05-28T19:00:04.332734   
5185  2025-05-28T19:00:06.100435   
5186  2025-05-28T19:00:07.840335   

                                            description  \
0     DISPONIBLE DE MANERA INMEDIATA HousinGo presen...   
1     DISPONIBLE A PARTIR DEL 25 DE JUNIO DE 2025 Ho...   
2     DISPONIBLE A PARTIR DEL 23 DE JUNIO DE 2025! D...   
3     ¡Oportunidad de alquiler! Este luminoso piso e...   
4     ¡¡Piso totalmente reformado, a estrenar, 2 dor...   
...                                                 ...   
5182  Agencia inmobiliaria de MADRID VALLECAS - Zona...   
5183  La Inmobiliaria Internacional CPM gestiona est...   
5184  Lujo, vistas y confort a un paso de Madrid Des...   
5185  *********grupo inmara inmobiliaria************...   
5186  Este espectacular ático de 140 m² se encuentra...   

     energy_cert_classification  ... trastero vidrios_dobles  \
0        Pendiente de completar  ...    False          False   
1                    En trámite  ...    False          False   
2                    En trámite  ...    False          False   
3                    En trámite  ...    False          False   
4                    Disponible  ...    False          False   
...                         ...  ...      ...            ...   
5182                 Disponible  ...    False          False   
5183     Pendiente de completar  ...    False          False   
5184                 Disponible  ...    False          False   
5185                 En trámite  ...     True          False   
5186     Pendiente de completar  ...    False          False   

      energy_consumption_kwh_m2_yr  energy_emissions_kg_co2_m2_yr  \
0                              NaN                            NaN   
1                              NaN                            NaN   
2                              NaN                            NaN   
3                              NaN     

In [127]:
df = df.replace({np.nan: None})

In [111]:
df["description"].str.len().max()

5574

In [114]:
df["url"].str.len().max()

103

### Insertar datos en la base de datos

 La estrategia de trabajo será ir creando los df correspondientes a cada tabla de sql, rellenando las tablas independientes primero. El orden es el siguiente

age_range
– todos los rangos de antigüedad

feature_catalog
– lista de features (“ascensor”, “balcón”, …)

location
– todos los barrios/distritos.

si el estado de conservacion es una tabla hay que insertarla antes que property

property
– insertar las viviendas tras insertar location y age_range.
– Usando el location_id y el age_range_id resultantes.

listing
– Con property_id ya presente, se pueden cargar los anuncios.

si el estado del certificado energetico es una tabla aperte hay que insertarla antes que energy certificate

energy_certificate
– Solo para las propiedades que tengan certificado, usando su property_id.

property_feature
– Finalmente, para cada tupla (property_id, feature_id, valor)

Tabla `Conservacion`

In [117]:
df["conservacion"].str.len().max()


14.0

Tabla `energy_classification`

In [120]:
df["energy_cert_classification"].str.len().max()

22

### Tabla ``age_range``

In [ ]:
df["antiguedad"]

In [129]:
df["antiguedad"].dropna().unique().tolist()

['Más de 50 años',
 'Entre 20 y 30 años',
 'Entre 30 y 50 años',
 'Entre 5 y 10 años',
 'Menos de 5 años',
 'Entre 10 y 20 años']

In [131]:
age_range = df["antiguedad"].dropna().unique().tolist()

In [132]:
age_range

['Más de 50 años',
 'Entre 20 y 30 años',
 'Entre 30 y 50 años',
 'Entre 5 y 10 años',
 'Menos de 5 años',
 'Entre 10 y 20 años']

creamos la sentencia de sql

In [133]:
sql_age = """INSERT INTO age_range(label) VALUES (%s)"""

In [134]:
cursor.executemany(sql_age, [(label,) for label in age_range])

In [135]:
conn.commit()

Guardamos el mapeo para saber que id tiene cada rango

In [136]:
cursor.execute("SELECT * FROM age_range")

In [137]:
ages = cursor.fetchall()
ages

[(6, 'Entre 10 y 20 años'),
 (2, 'Entre 20 y 30 años'),
 (3, 'Entre 30 y 50 años'),
 (4, 'Entre 5 y 10 años'),
 (1, 'Más de 50 años'),
 (5, 'Menos de 5 años')]

In [138]:
age_map = {label: age_range_id for age_range_id, label in ages}
age_map

{'Entre 10 y 20 años': 6,
 'Entre 20 y 30 años': 2,
 'Entre 30 y 50 años': 3,
 'Entre 5 y 10 años': 4,
 'Más de 50 años': 1,
 'Menos de 5 años': 5}

### Tabla ``feature_map``

INSERT INTO feature_catalog(nombre) VALUES
  ('ascensor'),
  ('balcon'),
  ('calefaccion'),
  ('chimenea'),
  ('exterior'),
  ('garaje'),
  ('piscina'),
  ('trastero'),
  ('jardin'),
  ('adaptado_pmreducida'),
  ('aire_acondicionado'),
  ('puerta_blindada'),
  ('vidrios_dobles'),
  ('sistema_seguridad'),
  ('terraza'),
  ('amueblado'),
  ('cocina_equipada');

In [139]:
features = [
    'ascensor',
    'balcón',
    'calefacción',
    'chimenea',
    'exterior',
    'garaje',
    'piscina',
    'trastero',
    'jardín',
    'adaptado_pmreducida',
    'aire_acondicionado',
    'puerta_blindada',
    'vidrios_dobles',
    'sistema_seguridad',
    'terraza',
    'amueblado',
    'cocina_equipada',
    'orientacion_list',
    'gasto_comunidad_eur',
    'acepta_mascotas'
]

In [140]:
sql_feature = """INSERT INTO feature_catalog(nombre) VALUES (%s)"""

In [142]:
cursor.executemany(sql_feature, [(f,) for f in features])

In [143]:
conn.commit()

Extraer el mapeo de la base de datos

In [144]:
cursor.execute("SELECT * FROM feature_catalog")

In [145]:
f = cursor.fetchall()
f

[(20, 'acepta_mascotas'),
 (10, 'adaptado_pmreducida'),
 (11, 'aire_acondicionado'),
 (16, 'amueblado'),
 (1, 'ascensor'),
 (2, 'balcón'),
 (3, 'calefacción'),
 (4, 'chimenea'),
 (17, 'cocina_equipada'),
 (5, 'exterior'),
 (6, 'garaje'),
 (19, 'gasto_comunidad_eur'),
 (9, 'jardín'),
 (18, 'orientacion_list'),
 (7, 'piscina'),
 (12, 'puerta_blindada'),
 (14, 'sistema_seguridad'),
 (15, 'terraza'),
 (8, 'trastero'),
 (13, 'vidrios_dobles')]

In [146]:
feature_map = {nombre: feature_id for feature_id, nombre in f}
feature_map

{'acepta_mascotas': 20,
 'adaptado_pmreducida': 10,
 'aire_acondicionado': 11,
 'amueblado': 16,
 'ascensor': 1,
 'balcón': 2,
 'calefacción': 3,
 'chimenea': 4,
 'cocina_equipada': 17,
 'exterior': 5,
 'garaje': 6,
 'gasto_comunidad_eur': 19,
 'jardín': 9,
 'orientacion_list': 18,
 'piscina': 7,
 'puerta_blindada': 12,
 'sistema_seguridad': 14,
 'terraza': 15,
 'trastero': 8,
 'vidrios_dobles': 13}

### Tabla ``Location``

In [147]:
df[["barrio","distrito"]].drop_duplicates()

barrio            distrito
0           Castellana           Salamanca
1            Río Rosas            Chamberí
3     Fuente del Berro           Salamanca
4      Justicia-Chueca              Centro
5              Aravaca     Moncloa-Aravaca
...                ...                 ...
2477          Portazgo  Puente de Vallecas
2493  Apóstol Santiago           Hortaleza
2926  Centro Histórico           Vicálvaro
3557           Horcajo           Moratalaz
4172        Aeropuerto             Barajas

[138 rows x 2 columns]

In [148]:
df_location = df[["barrio","distrito"]].drop_duplicates()
df_location

barrio            distrito
0           Castellana           Salamanca
1            Río Rosas            Chamberí
3     Fuente del Berro           Salamanca
4      Justicia-Chueca              Centro
5              Aravaca     Moncloa-Aravaca
...                ...                 ...
2477          Portazgo  Puente de Vallecas
2493  Apóstol Santiago           Hortaleza
2926  Centro Histórico           Vicálvaro
3557           Horcajo           Moratalaz
4172        Aeropuerto             Barajas

[138 rows x 2 columns]

In [149]:
df_location.isna().sum()

barrio      1
distrito    1
dtype: int64

In [150]:
df_location = df_location.dropna()

Pasamos a tupla para poder insertar

In [151]:
locations = [tuple(x) for x in df_location.values]
locations

[('Castellana', 'Salamanca'),
 ('Río Rosas', 'Chamberí'),
 ('Fuente del Berro', 'Salamanca'),
 ('Justicia-Chueca', 'Centro'),
 ('Aravaca', 'Moncloa-Aravaca'),
 ('Rejas', 'San Blas'),
 ('Berruguete', 'Tetuán'),
 ('Simancas', 'San Blas'),
 ('Ibiza', 'Retiro'),
 ('Mirasierra-Arroyo del Fresno', 'Fuencarral-El Pardo'),
 ('Lista', 'Salamanca'),
 ('Recoletos', 'Salamanca'),
 ('Buenavista', 'Carabanchel'),
 ('Puerta del Ángel', 'Latina'),
 ('Pinar del Rey', 'Hortaleza'),
 ('El Viso', 'Chamartín'),
 ('Atocha', 'Arganzuela'),
 ('Almagro', 'Chamberí'),
 ('Peñagrande', 'Fuencarral-El Pardo'),
 ('Niño Jesús', 'Retiro'),
 ('Imperial', 'Arganzuela'),
 ('Trafalgar', 'Chamberí'),
 ('Palacio', 'Centro'),
 ('Valdeacederas', 'Tetuán'),
 ('Estrella', 'Retiro'),
 ('El Cañaveral', 'Vicálvaro'),
 ('Chopera', 'Arganzuela'),
 ('Jerónimos', 'Retiro'),
 ('Arapiles', 'Chamberí'),
 ('Cuatro Caminos', 'Tetuán'),
 ('Almenara', 'Tetuán'),
 ('Opañel', 'Carabanchel'),
 ('San Pascual', 'Ciudad Lineal'),
 ('Universidad-M

In [152]:
sql_loc = """INSERT INTO location (barrio, distrito) VALUES (%s, %s)"""

In [153]:
cursor.executemany(sql_loc, locations)

In [154]:
conn.commit()

mapeo de location_id

In [155]:
cursor.execute("SELECT * FROM location")

In [156]:
l = cursor.fetchall()
l

[(1, 'Castellana', 'Salamanca'),
 (2, 'Río Rosas', 'Chamberí'),
 (3, 'Fuente del Berro', 'Salamanca'),
 (4, 'Justicia-Chueca', 'Centro'),
 (5, 'Aravaca', 'Moncloa-Aravaca'),
 (6, 'Rejas', 'San Blas'),
 (7, 'Berruguete', 'Tetuán'),
 (8, 'Simancas', 'San Blas'),
 (9, 'Ibiza', 'Retiro'),
 (10, 'Mirasierra-Arroyo del Fresno', 'Fuencarral-El Pardo'),
 (11, 'Lista', 'Salamanca'),
 (12, 'Recoletos', 'Salamanca'),
 (13, 'Buenavista', 'Carabanchel'),
 (14, 'Puerta del Ángel', 'Latina'),
 (15, 'Pinar del Rey', 'Hortaleza'),
 (16, 'El Viso', 'Chamartín'),
 (17, 'Atocha', 'Arganzuela'),
 (18, 'Almagro', 'Chamberí'),
 (19, 'Peñagrande', 'Fuencarral-El Pardo'),
 (20, 'Niño Jesús', 'Retiro'),
 (21, 'Imperial', 'Arganzuela'),
 (22, 'Trafalgar', 'Chamberí'),
 (23, 'Palacio', 'Centro'),
 (24, 'Valdeacederas', 'Tetuán'),
 (25, 'Estrella', 'Retiro'),
 (26, 'El Cañaveral', 'Vicálvaro'),
 (27, 'Chopera', 'Arganzuela'),
 (28, 'Jerónimos', 'Retiro'),
 (29, 'Arapiles', 'Chamberí'),
 (30, 'Cuatro Caminos', 'Tet

In [157]:
loc_map = {
    (barrio, distrito): location_id
    for location_id, barrio, distrito in l
}

loc_map

{('Castellana', 'Salamanca'): 1,
 ('Río Rosas', 'Chamberí'): 2,
 ('Fuente del Berro', 'Salamanca'): 3,
 ('Justicia-Chueca', 'Centro'): 4,
 ('Aravaca', 'Moncloa-Aravaca'): 5,
 ('Rejas', 'San Blas'): 6,
 ('Berruguete', 'Tetuán'): 7,
 ('Simancas', 'San Blas'): 8,
 ('Ibiza', 'Retiro'): 9,
 ('Mirasierra-Arroyo del Fresno', 'Fuencarral-El Pardo'): 10,
 ('Lista', 'Salamanca'): 11,
 ('Recoletos', 'Salamanca'): 12,
 ('Buenavista', 'Carabanchel'): 13,
 ('Puerta del Ángel', 'Latina'): 14,
 ('Pinar del Rey', 'Hortaleza'): 15,
 ('El Viso', 'Chamartín'): 16,
 ('Atocha', 'Arganzuela'): 17,
 ('Almagro', 'Chamberí'): 18,
 ('Peñagrande', 'Fuencarral-El Pardo'): 19,
 ('Niño Jesús', 'Retiro'): 20,
 ('Imperial', 'Arganzuela'): 21,
 ('Trafalgar', 'Chamberí'): 22,
 ('Palacio', 'Centro'): 23,
 ('Valdeacederas', 'Tetuán'): 24,
 ('Estrella', 'Retiro'): 25,
 ('El Cañaveral', 'Vicálvaro'): 26,
 ('Chopera', 'Arganzuela'): 27,
 ('Jerónimos', 'Retiro'): 28,
 ('Arapiles', 'Chamberí'): 29,
 ('Cuatro Caminos', 'Tetuán'

### Tabla ``property`` 

In [159]:
# eliminamos las filas donde no hay ni barrio ni distrito

df = df.dropna(subset=["barrio","distrito"], how="all")

In [164]:
df[[
    "barrio","distrito",
    "latitude","longitude",
    "property_id",
    "superficie_construida","superficie_util",
    "habitaciones","banos","planta_numerica",
    "conservacion","antiguedad",
    "amueblado","cocina_equipada"
]].drop_duplicates()

barrio            distrito   latitude longitude  \
0           Castellana           Salamanca  40.434281 -3.686286   
1            Río Rosas            Chamberí  40.438612 -3.699901   
2           Castellana           Salamanca  40.435237 -3.683515   
3     Fuente del Berro           Salamanca  40.429047 -3.666474   
4      Justicia-Chueca              Centro  40.422607 -3.699196   
...                ...                 ...        ...       ...   
5182          Portazgo  Puente de Vallecas  40.383712 -3.650452   
5183      Pueblo Nuevo       Ciudad Lineal  40.426333 -3.638205   
5184        Valdemarín     Moncloa-Aravaca  40.465343 -3.762967   
5185         Trafalgar            Chamberí  40.435597 -3.700479   
5186               Sol              Centro  40.415001 -3.706658   

             property_id superficie_construida superficie_util habitaciones  \
0     51740663097.108894                 272.0            None          4.0   
1     54233688682.108894                  74.0            None          1.0   
2     54235652798.108894                 101.0           100.0          3.0   
3           575224267.44                  65.0            50.0          3.0   
4     52524614200.100494                  83.0            77.0          2.0   
...                  ...                   ...             ...          ...   
5182  52563480033.100197                 113.0            None          3.0   
5183  53416734952.100494                 130.0           120.0          3.0   
5184  54215178083.101799                 239.0            None          4.0   
5185  53382416766.108894                 185.0           160.0          4.0   
5186  48431058024.100494                 139.0            None          2.0   

     banos planta_numerica    conservacion          antiguedad amueblado  \
0      5.0             6.0      A estrenar                None      None   
1      1.0             6.0  En buen estado                None      True   
2      1.0             2.0  En buen estado                None      True   
3      1.0             6.0  En buen estado      Más de 50 años      True   
4      2.0             5.0            None      Más de 50 años      True   
...    ...             ...             ...                 ...       ...   
5182   2.0             2.0       Reformado  Entre 30 y 50 años      None   
5183   2.0            None  En buen estado      Más de 50 años      None   
5184   4.0             2.0            None  Entre 20 y 30 años      None   
5185   3.0             4.0            None                None      True   
5186   2.0             5.0  En buen estado                None      None   

      cocina_equipada  
0                True  
1                True  
2               False  
3                True  
4               False  
...               ...  
5182             True  
5183            False  
5184            False  
5185             True  
5186            False  

[5156 rows x 14 columns]

In [165]:
df_property = df[[
    "barrio","distrito",
    "latitude","longitude",
    "property_id",
    "superficie_construida","superficie_util",
    "habitaciones","banos","planta_numerica",
    "conservacion","antiguedad",
    "amueblado","cocina_equipada"
]].drop_duplicates()

df_property

barrio            distrito   latitude longitude  \
0           Castellana           Salamanca  40.434281 -3.686286   
1            Río Rosas            Chamberí  40.438612 -3.699901   
2           Castellana           Salamanca  40.435237 -3.683515   
3     Fuente del Berro           Salamanca  40.429047 -3.666474   
4      Justicia-Chueca              Centro  40.422607 -3.699196   
...                ...                 ...        ...       ...   
5182          Portazgo  Puente de Vallecas  40.383712 -3.650452   
5183      Pueblo Nuevo       Ciudad Lineal  40.426333 -3.638205   
5184        Valdemarín     Moncloa-Aravaca  40.465343 -3.762967   
5185         Trafalgar            Chamberí  40.435597 -3.700479   
5186               Sol              Centro  40.415001 -3.706658   

             property_id superficie_construida superficie_util habitaciones  \
0     51740663097.108894                 272.0            None          4.0   
1     54233688682.108894                  74.0            None          1.0   
2     54235652798.108894                 101.0           100.0          3.0   
3           575224267.44                  65.0            50.0          3.0   
4     52524614200.100494                  83.0            77.0          2.0   
...                  ...                   ...             ...          ...   
5182  52563480033.100197                 113.0            None          3.0   
5183  53416734952.100494                 130.0           120.0          3.0   
5184  54215178083.101799                 239.0            None          4.0   
5185  53382416766.108894                 185.0           160.0          4.0   
5186  48431058024.100494                 139.0            None          2.0   

     banos planta_numerica    conservacion          antiguedad amueblado  \
0      5.0             6.0      A estrenar                None      None   
1      1.0             6.0  En buen estado                None      True   
2      1.0             2.0  En buen estado                None      True   
3      1.0             6.0  En buen estado      Más de 50 años      True   
4      2.0             5.0            None      Más de 50 años      True   
...    ...             ...             ...                 ...       ...   
5182   2.0             2.0       Reformado  Entre 30 y 50 años      None   
5183   2.0            None  En buen estado      Más de 50 años      None   
5184   4.0             2.0            None  Entre 20 y 30 años      None   
5185   3.0             4.0            None                None      True   
5186   2.0             5.0  En buen estado                None      None   

      cocina_equipada  
0                True  
1                True  
2               False  
3                True  
4               False  
...               ...  
5182             True  
5183            False  
5184            False  
5185             True  
5186            False  

[5156 rows x 14 columns]

In [167]:
df_property = df_property.rename(columns={
    "property_id":      "property_native_id",
    "planta_numerica":  "planta",
    "conservacion":     "estado_conservacion",
})

Contruimos la lista de tuplas para insertar

In [170]:
property_records = []
for _, row in df_property.iterrows():
    loc_id = loc_map.get((row.barrio, row.distrito))
    age_id = age_map.get(row.antiguedad)

    habitaciones = int(row.habitaciones) if row.habitaciones is not None else None
    banos        = int(row.banos)         if row.banos        is not None else None
    planta       = int(row.planta)        if row.planta       is not None else None

    property_records.append((
        loc_id,
        row.latitude,
        row.longitude,
        row.property_native_id,
        row.superficie_construida,
        row.superficie_util,
        habitaciones,
        banos,
        planta,
        row.estado_conservacion,
        age_id

    ))

In [171]:
property_records

[(1,
  40.4342811,
  -3.6862864,
  51740663097.108894,
  272.0,
  None,
  4,
  5,
  6,
  'A estrenar',
  None),
 (2,
  40.4386119,
  -3.6999008,
  54233688682.108894,
  74.0,
  None,
  1,
  1,
  6,
  'En buen estado',
  None),
 (1,
  40.4352372,
  -3.6835148,
  54235652798.108894,
  101.0,
  100.0,
  3,
  1,
  2,
  'En buen estado',
  None),
 (3,
  40.4290471,
  -3.6664739,
  575224267.44,
  65.0,
  50.0,
  3,
  1,
  6,
  'En buen estado',
  1),
 (4, 40.4226065, -3.6991962, 52524614200.100494, 83.0, 77.0, 2, 2, 5, None, 1),
 (5,
  40.4446662,
  -3.7879384,
  45072351463.1018,
  90.0,
  None,
  2,
  1,
  2,
  None,
  None),
 (6,
  40.4430413,
  -3.5754374,
  54187238191.101,
  81.0,
  62.0,
  1,
  1,
  None,
  'En buen estado',
  None),
 (4,
  40.425045,
  -3.6990557,
  50050215109.99223,
  28.0,
  28.0,
  None,
  1,
  0,
  'A estrenar',
  1),
 (7,
  40.4621,
  -3.70241,
  53383290265.100494,
  50.0,
  49.0,
  1,
  1,
  1,
  'En buen estado',
  None),
 (8,
  40.4354744,
  -3.6207605,
  

In [175]:
sql_property = """
        INSERT INTO property
        (location_id, latitude, longitude,
        property_native_id,
        superficie_construida, superficie_util,
        habitaciones, banos, planta,
        estado_conservacion, age_range_id)
        VALUES
        (%s,%s,%s,
        %s,
        %s,%s,
        %s,%s,%s,
        %s,%s)
    """

In [176]:
cursor.executemany(sql_property, property_records)

In [177]:
conn.commit()

### mapeo de las ids de la tabla property

In [196]:
cursor.execute("SELECT property_id, property_native_id FROM property")

In [197]:
p = cursor.fetchall()
p

[(4156, '11683122104.1001'),
 (3059, '11713976246.1005'),
 (789, '12520879287.996542'),
 (705, '13384785496.996542'),
 (63, '13401653773.1005'),
 (769, '15065560922.996542'),
 (2005, '15091421027.1021'),
 (737, '15094991482.996542'),
 (75, '15882091149.518978'),
 (1119, '16755127185.1005'),
 (780, '16755913201.516598'),
 (881, '1676213431.996542'),
 (756, '17500082181.1005'),
 (845, '1750037059.996542'),
 (250, '17598322130.1005'),
 (2666, '1772946757.1097'),
 (222, '18366550285.1005'),
 (4060, '19168697534.517094'),
 (4556, '19173521149.517094'),
 (4346, '19178660789.517094'),
 (4259, '19197237241.996544'),
 (4237, '19199665125.517094'),
 (934, '19220092216.517094'),
 (938, '19240687566.51897'),
 (83, '19260801217.517094'),
 (1033, '19261761023.517094'),
 (753, '20006412977.996544'),
 (279, '20041996024.1092'),
 (1497, '20049394249.1005'),
 (1027, '20057768451.1005'),
 (344, '20084069014.1092'),
 (3116, '20839223003.1492'),
 (5102, '20905432544.52015'),
 (1395, '21670182341.1005'),
 (

In [198]:
property_map = {native: pid for pid, native in p}
property_map


{'11683122104.1001': 4156,
 '11713976246.1005': 3059,
 '12520879287.996542': 789,
 '13384785496.996542': 705,
 '13401653773.1005': 63,
 '15065560922.996542': 769,
 '15091421027.1021': 2005,
 '15094991482.996542': 737,
 '15882091149.518978': 75,
 '16755127185.1005': 1119,
 '16755913201.516598': 780,
 '1676213431.996542': 881,
 '17500082181.1005': 756,
 '1750037059.996542': 845,
 '17598322130.1005': 250,
 '1772946757.1097': 2666,
 '18366550285.1005': 222,
 '19168697534.517094': 4060,
 '19173521149.517094': 4556,
 '19178660789.517094': 4346,
 '19197237241.996544': 4259,
 '19199665125.517094': 4237,
 '19220092216.517094': 934,
 '19240687566.51897': 938,
 '19260801217.517094': 83,
 '19261761023.517094': 1033,
 '20006412977.996544': 753,
 '20041996024.1092': 279,
 '20049394249.1005': 1497,
 '20057768451.1005': 1027,
 '20084069014.1092': 344,
 '20839223003.1492': 3116,
 '20905432544.52015': 5102,
 '21670182341.1005': 1395,
 '21711813995.1005': 1256,
 '21725441885.1018': 31,
 '21727250593.5193

### Tabla ``listing``

In [184]:
df["scrape_status"] = "ok"

In [188]:
df_listing = df[["property_id","url", "listing_type", "price_kind", "price_eur","scraped_at","scrape_status","description"]]
df_listing

property_id                                                url  \
0     51740663097.108894  https://www.pisos.com/alquilar/atico-salamanca...   
1     54233688682.108894  https://www.pisos.com/alquilar/atico-rio_rosas...   
2     54235652798.108894  https://www.pisos.com/alquilar/piso-salamanca_...   
3           575224267.44  https://www.pisos.com/alquilar/piso-fuente_del...   
4     52524614200.100494  https://www.pisos.com/alquilar/piso-justicia_c...   
...                  ...                                                ...   
5182  52563480033.100197  https://www.pisos.com/comprar/piso-puente_de_v...   
5183  53416734952.100494  https://www.pisos.com/comprar/piso-ciudad_line...   
5184  54215178083.101799  https://www.pisos.com/comprar/atico-valdemarin...   
5185  53382416766.108894  https://www.pisos.com/comprar/piso-trafalgar28...   
5186  48431058024.100494  https://www.pisos.com/comprar/atico-sol_barrio...   

     listing_type  price_kind  price_eur                  scraped_at  \
0          rental  rent_month    10000.0  2025-05-28T19:53:30.586256   
1          rental  rent_month     1450.0  2025-05-28T19:53:32.370621   
2          rental  rent_month     2200.0  2025-05-28T19:53:34.120400   
3          rental  rent_month     1700.0  2025-05-28T19:53:35.912036   
4          rental  rent_month     2650.0  2025-05-28T19:53:37.641884   
...           ...         ...        ...                         ...   
5182         sale  sale_price   279000.0  2025-05-28T19:00:00.644476   
5183         sale  sale_price   411000.0  2025-05-28T19:00:02.401578   
5184         sale  sale_price  1550000.0  2025-05-28T19:00:04.332734   
5185         sale  sale_price  2490000.0  2025-05-28T19:00:06.100435   
5186         sale  sale_price  2460000.0  2025-05-28T19:00:07.840335   

     scrape_status                                        description  
0               ok  DISPONIBLE DE MANERA INMEDIATA HousinGo presen...  
1               ok  DISPONIBLE A PARTIR DEL 25 DE JUNIO DE 2025 Ho...  
2               ok  DISPONIBLE A PARTIR DEL 23 DE JUNIO DE 2025! D...  
3               ok  ¡Oportunidad de alquiler! Este luminoso piso e...  
4               ok  ¡¡Piso totalmente reformado, a estrenar, 2 dor...  
...            ...                                                ...  
5182            ok  Agencia inmobiliaria de MADRID VALLECAS - Zona...  
5183            ok  La Inmobiliaria Internacional CPM gestiona est...  
5184            ok  Lujo, vistas y confort a un paso de Madrid Des...  
5185            ok  *********grupo inmara inmobiliaria************...  
5186            ok  Este espectacular ático de 140 m² se encuentra...  

[5156 rows x 8 columns]

In [195]:
property_map

{'11683122104.1001': 4156,
 '11713976246.1005': 3059,
 '12520879287.996542': 789,
 '13384785496.996542': 705,
 '13401653773.1005': 63,
 '15065560922.996542': 769,
 '15091421027.1021': 2005,
 '15094991482.996542': 737,
 '15882091149.518978': 75,
 '16755127185.1005': 1119,
 '16755913201.516598': 780,
 '1676213431.996542': 881,
 '17500082181.1005': 756,
 '1750037059.996542': 845,
 '17598322130.1005': 250,
 '1772946757.1097': 2666,
 '18366550285.1005': 222,
 '19168697534.517094': 4060,
 '19173521149.517094': 4556,
 '19178660789.517094': 4346,
 '19197237241.996544': 4259,
 '19199665125.517094': 4237,
 '19220092216.517094': 934,
 '19240687566.51897': 938,
 '19260801217.517094': 83,
 '19261761023.517094': 1033,
 '20006412977.996544': 753,
 '20041996024.1092': 279,
 '20049394249.1005': 1497,
 '20057768451.1005': 1027,
 '20084069014.1092': 344,
 '20839223003.1492': 3116,
 '20905432544.52015': 5102,
 '21670182341.1005': 1395,
 '21711813995.1005': 1256,
 '21725441885.1018': 31,
 '21727250593.5193

In [207]:
list_records = []
for _, row in df_listing.iterrows():
    pid = property_map.get(str(row.property_id))
    
    if pid is None:
        continue
    list_records.append((
        pid,
        row.url,
        row.listing_type,
        row.price_kind,
        row.price_eur,
        row.scraped_at,
        row.scrape_status,
        row.description
    ))

list_records

[(1,
  'https://www.pisos.com/alquilar/atico-salamanca_castellana28006-51740663097_108900/',
  'rental',
  'rent_month',
  10000.0,
  '2025-05-28T19:53:30.586256',
  'ok',
  'DISPONIBLE DE MANERA INMEDIATA HousinGo presenta este impresionante ático dúplex con terrazas, situado en la calle Serrano, en una de las zonas más distinguidas del barrio de Salamanca. A escasos pasos de la Embajada de Estados Unidos y el Museo Lázaro Galdiano, su ubicación privilegiada ofrece un entorno de lujo rodeado de exclusivas boutiques, restaurantes de alta cocina y servicios de primer nivel. El ático se encuentra en un edificio clásico rehabilitado interiormente, que conserva su encanto original con un toque moderno. La finca dispone de servicio de portero físico, dos ascensores principales más uno de servicio y amplias zonas comunes en excelente estado, con la futura incorporación de un gimnasio para el disfrute de sus residentes. Además, incluye dos plazas de garaje de acceso directo y un trastero, aña

In [208]:
sql_listing = """
            INSERT INTO listing
            (property_id, url, listing_type, price_kind, price_eur, scraped_at, scrape_status, description)
            VALUES
            (%s,%s,%s,%s,%s,%s,%s,%s)
      """

In [209]:
cursor.executemany(sql_listing, list_records)

In [210]:
conn.commit()

In [211]:
cursor.rowcount

5156

In [212]:
df_listing.shape

(5156, 8)

#### Mapeo de la id de la tabla listing

In [213]:
cursor.execute("""
  SELECT l.listing_id, p.property_native_id
    FROM listing l
    JOIN property p USING(property_id)
""")

In [214]:
l = cursor.fetchall()
l

[(4156, '11683122104.1001'),
 (3059, '11713976246.1005'),
 (789, '12520879287.996542'),
 (705, '13384785496.996542'),
 (63, '13401653773.1005'),
 (769, '15065560922.996542'),
 (2005, '15091421027.1021'),
 (737, '15094991482.996542'),
 (75, '15882091149.518978'),
 (1119, '16755127185.1005'),
 (780, '16755913201.516598'),
 (881, '1676213431.996542'),
 (756, '17500082181.1005'),
 (845, '1750037059.996542'),
 (250, '17598322130.1005'),
 (2666, '1772946757.1097'),
 (222, '18366550285.1005'),
 (4060, '19168697534.517094'),
 (4556, '19173521149.517094'),
 (4346, '19178660789.517094'),
 (4259, '19197237241.996544'),
 (4237, '19199665125.517094'),
 (934, '19220092216.517094'),
 (938, '19240687566.51897'),
 (83, '19260801217.517094'),
 (1033, '19261761023.517094'),
 (753, '20006412977.996544'),
 (279, '20041996024.1092'),
 (1497, '20049394249.1005'),
 (1027, '20057768451.1005'),
 (344, '20084069014.1092'),
 (3116, '20839223003.1492'),
 (5102, '20905432544.52015'),
 (1395, '21670182341.1005'),
 (

In [215]:
listing_map = { native: lid for lid, native in l }
listing_map

{'11683122104.1001': 4156,
 '11713976246.1005': 3059,
 '12520879287.996542': 789,
 '13384785496.996542': 705,
 '13401653773.1005': 63,
 '15065560922.996542': 769,
 '15091421027.1021': 2005,
 '15094991482.996542': 737,
 '15882091149.518978': 75,
 '16755127185.1005': 1119,
 '16755913201.516598': 780,
 '1676213431.996542': 881,
 '17500082181.1005': 756,
 '1750037059.996542': 845,
 '17598322130.1005': 250,
 '1772946757.1097': 2666,
 '18366550285.1005': 222,
 '19168697534.517094': 4060,
 '19173521149.517094': 4556,
 '19178660789.517094': 4346,
 '19197237241.996544': 4259,
 '19199665125.517094': 4237,
 '19220092216.517094': 934,
 '19240687566.51897': 938,
 '19260801217.517094': 83,
 '19261761023.517094': 1033,
 '20006412977.996544': 753,
 '20041996024.1092': 279,
 '20049394249.1005': 1497,
 '20057768451.1005': 1027,
 '20084069014.1092': 344,
 '20839223003.1492': 3116,
 '20905432544.52015': 5102,
 '21670182341.1005': 1395,
 '21711813995.1005': 1256,
 '21725441885.1018': 31,
 '21727250593.5193

### Tabla `rental_term`

esta tabla la borraremos

### Tabla `energy_certificate`

In [216]:
df_energy = df[["property_id","energy_cert_classification","energy_consumption_rating","energy_emissions_rating","energy_emissions_kg_co2_m2_yr","energy_consumption_kwh_m2_yr"]]
df_energy

property_id energy_cert_classification energy_consumption_rating  \
0     51740663097.108894     Pendiente de completar                      None   
1     54233688682.108894                 En trámite                      None   
2     54235652798.108894                 En trámite                      None   
3           575224267.44                 En trámite                      None   
4     52524614200.100494                 Disponible                         D   
...                  ...                        ...                       ...   
5182  52563480033.100197                 Disponible                         E   
5183  53416734952.100494     Pendiente de completar                      None   
5184  54215178083.101799                 Disponible                         D   
5185  53382416766.108894                 En trámite                      None   
5186  48431058024.100494     Pendiente de completar                      None   

     energy_emissions_rating energy_emissions_kg_co2_m2_yr  \
0                       None                          None   
1                       None                          None   
2                       None                          None   
3                       None                          None   
4                          D                          22.0   
...                      ...                           ...   
5182                       E                          44.0   
5183                    None                          None   
5184                       D                          27.0   
5185                    None                          None   
5186                    None                          None   

     energy_consumption_kwh_m2_yr  
0                            None  
1                            None  
2                            None  
3                            None  
4                           110.0  
...                           ...  
5182                        211.0  
5183                         None  
5184                        132.0  
5185                         None  
5186                         None  

[5156 rows x 6 columns]

Lista de tuplas a insertar

In [220]:
energy_records = []
for _, row in df_energy.iterrows():
    pid = property_map.get(str(row.property_id))
    clasificacion = row.energy_cert_classification
    consumo  = row.energy_consumption_rating
    emisiones = row.energy_emissions_rating

    emision_value = row.energy_emissions_kg_co2_m2_yr
    consumption_value = row.energy_consumption_kwh_m2_yr

    energy_records.append((pid, clasificacion, consumo, emisiones, emision_value, consumption_value))

energy_records

[(1, 'Pendiente de completar', None, None, None, None),
 (2, 'En trámite', None, None, None, None),
 (3, 'En trámite', None, None, None, None),
 (4, 'En trámite', None, None, None, None),
 (5, 'Disponible', 'D', 'D', 22.0, 110.0),
 (6, 'No indicado', None, None, None, None),
 (7, 'Pendiente de completar', None, None, None, None),
 (8, 'En trámite', None, None, None, None),
 (9, 'En trámite', None, None, None, None),
 (10, 'No indicado', None, None, None, None),
 (11, 'En trámite', None, None, None, None),
 (12, 'En trámite', None, None, None, None),
 (13, 'En trámite', None, None, None, None),
 (14, 'En trámite', None, None, None, None),
 (15, 'Disponible', 'E', 'D', 45.0, 187.0),
 (16, 'En trámite', None, None, None, None),
 (17, 'En trámite', None, None, None, None),
 (18, 'En trámite', None, None, None, None),
 (19, 'Pendiente de completar', None, None, None, None),
 (20, 'Disponible', 'E', 'E', 46.0, 221.0),
 (21, 'No indicado', None, None, None, None),
 (22, 'Disponible', 'C', 'C'

In [221]:
sql_energy = """
                INSERT INTO energy_certificate
                (property_id, classification, consumo_rating, emisiones_rating, emision_value, consumption_value)
                VALUES
                (%s,%s,%s,%s,%s,%s)
            """

In [222]:
cursor.executemany(sql_energy, energy_records)

In [223]:
conn.commit()

### Tabla `property_feature`

In [245]:
property_map

{'11683122104.1001': 4156,
 '11713976246.1005': 3059,
 '12520879287.996542': 789,
 '13384785496.996542': 705,
 '13401653773.1005': 63,
 '15065560922.996542': 769,
 '15091421027.1021': 2005,
 '15094991482.996542': 737,
 '15882091149.518978': 75,
 '16755127185.1005': 1119,
 '16755913201.516598': 780,
 '1676213431.996542': 881,
 '17500082181.1005': 756,
 '1750037059.996542': 845,
 '17598322130.1005': 250,
 '1772946757.1097': 2666,
 '18366550285.1005': 222,
 '19168697534.517094': 4060,
 '19173521149.517094': 4556,
 '19178660789.517094': 4346,
 '19197237241.996544': 4259,
 '19199665125.517094': 4237,
 '19220092216.517094': 934,
 '19240687566.51897': 938,
 '19260801217.517094': 83,
 '19261761023.517094': 1033,
 '20006412977.996544': 753,
 '20041996024.1092': 279,
 '20049394249.1005': 1497,
 '20057768451.1005': 1027,
 '20084069014.1092': 344,
 '20839223003.1492': 3116,
 '20905432544.52015': 5102,
 '21670182341.1005': 1395,
 '21711813995.1005': 1256,
 '21725441885.1018': 31,
 '21727250593.5193

In [224]:
df.columns

Index(['url', 'property_id', 'price_eur', 'barrio', 'distrito', 'latitude',
       'longitude', 'scraped_at', 'description', 'energy_cert_classification',
       'energy_consumption_rating', 'energy_emissions_rating',
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'antiguedad', 'armarios_empotrados', 'ascensor', 'balcon', 'banos',
       'calefaccion', 'chimenea', 'cocina_equipada', 'conservacion',
       'exterior', 'garaje', 'habitaciones', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad', 'superficie_construida',
       'superficie_util', 'terraza', 'trastero', 'vidrios_dobles',
       'energy_consumption_kwh_m2_yr', 'energy_emissions_kg_co2_m2_yr',
       'gastos_comunidad_eur', 'orientacion_list', 'planta_numerica',
       'acepta_mascotas', 'price_kind', 'listing_type', 'scrape_status'],
      dtype='object')

In [225]:
bool_cols = [
    
       'adaptado_movilidad_reducida', 'aire_acondicionado', 'amueblado',
       'armarios_empotrados', 'ascensor', 'balcon',
       'calefaccion', 'chimenea', 'cocina_equipada',
       'exterior', 'garaje', 'jardin', 'piscina',
       'puerta_blindada', 'sistema_seguridad',
       'terraza', 'trastero', 'vidrios_dobles',
       'gastos_comunidad_eur', 'orientacion_list',
       'acepta_mascotas'

]

In [227]:
[df[columna].unique() for columna in bool_cols]

[array([False,  True]),
 array([ True, False]),
 array([None, True, False], dtype=object),
 array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([ True, False]),
 array([ True, False]),
 array([ True, False]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([False,  True]),
 array([ True, False]),
 array([False,  True]),
 array([False,  True]),
 array([None, 0.0, 15.0, 70.0, 50.0, 100.0, 30.0, 90.0, 486.0, 200.0,
        250.0, 145.0, 156.0, 107.0, 120.0, 60.0, 545.0, 10.0, 290.0, 125.0,
        207.0, 45.0, 221.0, 185.0, 160.0, 177.0, 158.0, 104.0, 457.0,
        139.0, 380.0, 178.0, 130.0, 194.0, 341.0, 280.0, 800.0, 85.0,
        286.0, 650.0, 134.0, 165.0, 157.0, 240.0, 265.0, 220.0, 142.0,
        359.0, 1.0, 350.0, 132.0, 206.0, 140.0, 228.0, 450.0, 186.0, 440.0,
        684.0, 168.0, 378.0, 65.0, 246.0, 98.0, 620.0, 153.0, 216.0,
        1000.0, 180.0, 270.0, 358.0, 105.0, 57.

In [235]:
faltan = []
for clave in ["armarios_empotrados","gastos_comunidad_eur"]:
    if clave not in feature_map:
        faltan.append(clave)

faltan

['armarios_empotrados', 'gastos_comunidad_eur']

In [236]:
# Insertar las faltantes
cursor.executemany(
    "INSERT INTO feature_catalog(nombre) VALUES (%s)",
    [(f,) for f in faltan]
)

In [237]:
conn.commit()

In [238]:
cursor.execute("SELECT feature_id, nombre FROM feature_catalog")
feature_map = {nombre: fid for fid, nombre in cursor.fetchall()}
feature_map

{'acepta_mascotas': 20,
 'adaptado_pmreducida': 10,
 'aire_acondicionado': 11,
 'amueblado': 16,
 'armarios_empotrados': 21,
 'ascensor': 1,
 'balcón': 2,
 'calefacción': 3,
 'chimenea': 4,
 'cocina_equipada': 17,
 'exterior': 5,
 'garaje': 6,
 'gasto_comunidad_eur': 19,
 'gastos_comunidad_eur': 22,
 'jardín': 9,
 'orientacion_list': 18,
 'piscina': 7,
 'puerta_blindada': 12,
 'sistema_seguridad': 14,
 'terraza': 15,
 'trastero': 8,
 'vidrios_dobles': 13}

Mapeo entre columnas y nombre en feature map

In [239]:
col_to_feat = {
    "adaptado_movilidad_reducida":    "adaptado_pmreducida",
    "aire_acondicionado":            "aire_acondicionado",
    "amueblado":                     "amueblado",
    "armarios_empotrados":           "armarios_empotrados",
    "ascensor":                      "ascensor",
    "balcon":                        "balcón",
    "calefaccion":                   "calefacción",
    "chimenea":                      "chimenea",
    "cocina_equipada":               "cocina_equipada",
    "exterior":                      "exterior",
    "garaje":                        "garaje",
    "jardin":                        "jardín",
    "piscina":                       "piscina",
    "puerta_blindada":               "puerta_blindada",
    "sistema_seguridad":             "sistema_seguridad",
    "terraza":                       "terraza",
    "trastero":                      "trastero",
    "vidrios_dobles":                "vidrios_dobles",
    "gastos_comunidad_eur":          "gasto_comunidad_eur",
    "orientacion_list":              "orientacion_list",
    "acepta_mascotas":               "acepta_mascotas"
}

In [248]:
property_map

{'11683122104.1001': 4156,
 '11713976246.1005': 3059,
 '12520879287.996542': 789,
 '13384785496.996542': 705,
 '13401653773.1005': 63,
 '15065560922.996542': 769,
 '15091421027.1021': 2005,
 '15094991482.996542': 737,
 '15882091149.518978': 75,
 '16755127185.1005': 1119,
 '16755913201.516598': 780,
 '1676213431.996542': 881,
 '17500082181.1005': 756,
 '1750037059.996542': 845,
 '17598322130.1005': 250,
 '1772946757.1097': 2666,
 '18366550285.1005': 222,
 '19168697534.517094': 4060,
 '19173521149.517094': 4556,
 '19178660789.517094': 4346,
 '19197237241.996544': 4259,
 '19199665125.517094': 4237,
 '19220092216.517094': 934,
 '19240687566.51897': 938,
 '19260801217.517094': 83,
 '19261761023.517094': 1033,
 '20006412977.996544': 753,
 '20041996024.1092': 279,
 '20049394249.1005': 1497,
 '20057768451.1005': 1027,
 '20084069014.1092': 344,
 '20839223003.1492': 3116,
 '20905432544.52015': 5102,
 '21670182341.1005': 1395,
 '21711813995.1005': 1256,
 '21725441885.1018': 31,
 '21727250593.5193

In [250]:
df["property_id"]

0       51740663097.108894
1       54233688682.108894
2       54235652798.108894
3             575224267.44
4       52524614200.100494
               ...        
5182    52563480033.100197
5183    53416734952.100494
5184    54215178083.101799
5185    53382416766.108894
5186    48431058024.100494
Name: property_id, Length: 5156, dtype: object

In [252]:
df["property"] = df["property_id"].agg(str).map(property_map)
df["property"]

C:\Users\marta\AppData\Local\Temp\ipykernel_11424\1043367346.py:1: FutureWarning: using <class 'str'> in Series.agg cannot aggregate and has been deprecated. Use Series.transform to keep behavior unchanged.
  df["property"] = df["property_id"].agg(str).map(property_map)


0          1
1          2
2          3
3          4
4          5
        ... 
5182    5152
5183    5153
5184    5154
5185    5155
5186    5156
Name: property, Length: 5156, dtype: int64

In [253]:
pf_records = []
for _, row in df.iterrows():
    pid = row.property
    if pid is None:
        continue

    for df_col, feat_name in col_to_feat.items():
        val = row.get(df_col)
        if val is None:
            continue

        # orientacion_list → lista o string
        if df_col == "orientacion_list":
            if isinstance(val, (list, tuple)):
                v = ",".join(val)
            else:
                v = str(val)
            pf_records.append((pid, feature_map[feat_name], v))
        # gastos_comunidad_eur → número
        elif df_col == "gastos_comunidad_eur":
            pf_records.append((pid, feature_map[feat_name], str(val)))
        # resto: booleanos
        else:
            if val is True:
                pf_records.append((pid, feature_map[feat_name], "True"))

pf_records

[(1, 11, 'True'),
 (1, 1, 'True'),
 (1, 3, 'True'),
 (1, 17, 'True'),
 (1, 5, 'True'),
 (1, 6, 'True'),
 (1, 15, 'True'),
 (2, 16, 'True'),
 (2, 1, 'True'),
 (2, 3, 'True'),
 (2, 17, 'True'),
 (2, 5, 'True'),
 (2, 15, 'True'),
 (2, 18, "['S']"),
 (3, 16, 'True'),
 (3, 1, 'True'),
 (4, 16, 'True'),
 (4, 1, 'True'),
 (4, 3, 'True'),
 (4, 17, 'True'),
 (4, 5, 'True'),
 (4, 12, 'True'),
 (4, 15, 'True'),
 (4, 19, '0.0'),
 (4, 18, "['NO']"),
 (5, 11, 'True'),
 (5, 16, 'True'),
 (5, 21, 'True'),
 (5, 1, 'True'),
 (5, 2, 'True'),
 (5, 3, 'True'),
 (5, 18, "['SE']"),
 (6, 1, 'True'),
 (6, 3, 'True'),
 (6, 7, 'True'),
 (7, 21, 'True'),
 (7, 5, 'True'),
 (7, 7, 'True'),
 (7, 12, 'True'),
 (7, 14, 'True'),
 (7, 8, 'True'),
 (7, 18, "['SE']"),
 (8, 16, 'True'),
 (8, 21, 'True'),
 (8, 1, 'True'),
 (8, 3, 'True'),
 (8, 17, 'True'),
 (8, 12, 'True'),
 (8, 18, "['E']"),
 (9, 11, 'True'),
 (9, 16, 'True'),
 (9, 21, 'True'),
 (9, 17, 'True'),
 (9, 5, 'True'),
 (9, 6, 'True'),
 (9, 8, 'True'),
 (10, 11, 

In [254]:
sql_pf = """
            INSERT INTO property_feature
                (property_id, feature_id, valor)
            VALUES
                (%s,%s,%s)
        """
cursor.executemany(sql_pf, pf_records)
conn.commit()

In [255]:
cursor.close()
conn.close() 